
###Create new task
POST http://localhost:8080/tasks
Content-Type: application/json

{
    "name": "New Task",
    "description": "This is a new task."
}

###Create task without name
POST http://localhost:8080/tasks
Content-Type: application/json

{
    "name": "",
    "description": "This task has no name."
}

###Get All Tasks
GET http://localhost:8080/tasks

###Get task by id 1
GET http://localhost:8080/tasks/1

###Get task which doesn't exists
GET http://localhost:8080/tasks/100

###Update task
PUT http://localhost:8080/tasks/1
Content-Type: application/json

{
    "name": "Tasker",
    "description": "Changed Task.",
    "completed": true

}

###Delete Task
DELETE http://localhost:8080/tasks/1