
###Create new task
POST http://localhost:8080/tasks
Content-Type: application/json

{
    "name": "New Task",
    "description": "This is a new task."
}

###Create task without name
POST http://localhost:8080/tasks
Content-Type: application/json

{
    "name": "",
    "description": "This task has no name."
}

###Get All Tasks
GET http://localhost:8080/tasks