spring:
  application:
    name: Task Manager
  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanager
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: "aVeryLongSecretKeyThatIsAtLeast256BitsLongForHS256Algorithm12345"
  expiration: 86400000